Document: godot
Title: Debian godot Manual
Author: <insert document author here>
Abstract: This manual describes what godot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/godot/godot.sgml.gz

Format: postscript
Files: /usr/share/doc/godot/godot.ps.gz

Format: text
Files: /usr/share/doc/godot/godot.text.gz

Format: HTML
Index: /usr/share/doc/godot/html/index.html
Files: /usr/share/doc/godot/html/*.html
